/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.BolsistaController;
import controlador.FuncionarioController;
import controlador.ListaController;
import controlador.OperacaoController;
import controlador.ProdutoController;
import controlador.ServidorController;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Bolsista;
import modelo.Funcionario;
import modelo.Lista;
import modelo.Operacao;
import modelo.Produto;
import modelo.Servidor;
import modelo.Usuario;
import tableModel.ListaTableModel;
import tableModel.ProdutoTableModel;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 *
 */
public class JFrmLista extends javax.swing.JFrame {

   // private JFrame principal;
    private ProdutoTableModel produtoModel;
    private ListaTableModel listaModel;
    private final ProdutoController bc = new ProdutoController();
    private final ListaController lc = new ListaController();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    List listaUsuario;
    Usuario responsavel;
          
    public JFrmLista() {
        
        
        
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        produtoModel = new ProdutoTableModel(bc.listaProduto());
        OperacaoController oc = new OperacaoController();
        int ultimo1 = oc.buscaUltimo();
        listaModel = new ListaTableModel(lc.getListaIdOperacao(ultimo1));
        //jTblProduto.setModel(produtoModel);
       // principal = joutro;
                     
       
        
    }
    
    public void sendEmail() throws EmailException {

        SimpleEmail email = new SimpleEmail();

        email.setHostName("smtp.mail.yahoo.com");

        email.setSmtpPort(587);

        email.addTo(); //destinatario

        email.setFrom("teste@yahoo.com.br"); //quem está mandando

        email.setSubject("Sistema Almoxarifado - Controle de Estoque v.1.0");

        email.setMsg("Este é um e-mail automático, não é necessário respondê-lo, TESTE TESTE TESTE");
        email.setSSL(true);

        email.setAuthentication("teste@yahoo.com.br", "4884bjk"); //usario e senha que envia o email. NAO FUNCIOANA PQ NAO CRIAMOS O EMAIL

        email.send();

    }
    
    
//    private static void ativa() {
//        JFrmOperacao.setEnabled(true);
//    }
       
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtnOperacao = new javax.swing.ButtonGroup();
        BtnCliente = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCmbCampos = new javax.swing.JComboBox();
        jTxtProcura = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Operações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(35);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(35);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(35);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2683_32x32.png"))); // NOI18N
        jButton1.setText("Concluir (Sair)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11292_32x32.png"))); // NOI18N
        jButton2.setText("Excluir item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblProdutoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblProduto);

        jLabel1.setText("Campo para Busca:");

        jCmbCampos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum", "Produto", "Localizacao" }));
        jCmbCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCamposActionPerformed(evt);
            }
        });

        jTxtProcura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtProcuraKeyTyped(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2683_32x32.png"))); // NOI18N
        jButton7.setText("Adiciona Item");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jCmbCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtProcura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jTabbedPane1.addTab("Itens Totais", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizaTabelaLista(){
        OperacaoController oc = new OperacaoController();
        int ultimo2 = oc.buscaUltimo();
        listaModel = new ListaTableModel(lc.getListaIdOperacao(ultimo2));
        jTable1.setModel(listaModel);
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       // JFrmPrincipal frmPrincipal = new JFrmPrincipal();
       // frmPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jTxtProcuraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtProcuraKeyTyped
        String chave = jTxtProcura.getText();
        if(chave.equals("")){
            chave = String.valueOf(evt.getKeyChar());
        }else if (evt.getKeyChar() !='\b'){
            chave = chave + evt.getKeyChar();
        }
        switch (jCmbCampos.getSelectedIndex()){

            case 1: produtoModel = new ProdutoTableModel (bc.getProdutoNome(chave));
            break;
            case 2: produtoModel = new ProdutoTableModel (bc.getProdutoLocalizacao(chave));
            break;
        }
        //atribui o modelo a tabela
        jTblProduto.setModel(produtoModel);
    }//GEN-LAST:event_jTxtProcuraKeyTyped

    private void jCmbCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCamposActionPerformed
        if(jCmbCampos.getSelectedIndex()==0){
            produtoModel = new ProdutoTableModel(bc.listaProduto());
            jTblProduto.setModel(produtoModel);
        }
        jTxtProcura.requestFocus();
    }//GEN-LAST:event_jCmbCamposActionPerformed

    private void jTblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblProdutoMouseClicked
        ProdutoTableModel modelo = (ProdutoTableModel) jTblProduto.getModel();
        Produto produto = modelo.getProduto(jTblProduto.getSelectedRow());
        //JFrmProduto frmProduto = new JFrmProduto(produto);
        //frmProduto.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jTblProdutoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lista lista1 = null;
        try{
            ListaTableModel modelo = (ListaTableModel) jTable1.getModel();
            lista1 = modelo.getLista(jTable1.getSelectedRow());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "SELECIONE UM PRODUTO PARA EXCLUIR", "Controle de Estoque", JOptionPane.INFORMATION_MESSAGE);
        }
        ListaController lc = new ListaController();
        
        
        ////
        
        OperacaoController oc = new OperacaoController();
        ProdutoController pc = new ProdutoController();
            
        int ultimo = oc.buscaUltimo();
        String tipo = oc.buscaTipo(ultimo);
        System.out.println("TIPO: "+ tipo);
        Produto produto1 = null;
        produto1 = pc.geProdutoId(lista1.getIdLista());
        
        if(tipo.equals("S")){
            pc.aumentaQtd(lista1.getIdProduto(), lista1.getQuantidade());

        }
        else if(tipo.equals("E")){
            pc.diminuiQtd(lista1.getIdProduto(), lista1.getQuantidade());
            System.out.println("LOKO");
        }
        
        lc.excluir(lista1.getIdLista());
        atualizaTabelaLista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
       // try {
      //      sendEmail();
       //   JOptionPane.showMessageDialog(null,"Email enviado!!" );
      //  } catch (EmailException ex) {
        //    Logger.getLogger(JFrmOperacao.class.getName()).log(Level.SEVERE, null, ex);
        //}
        dispose();
        // jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Produto produto = null;
        try {
            ProdutoTableModel modelo = (ProdutoTableModel) jTblProduto.getModel();
            produto = modelo.getProduto(jTblProduto.getSelectedRow());
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "SELECIONE UM PRODUTO", "Controle de Estoque", JOptionPane.INFORMATION_MESSAGE);
        }
        if(produto != null && jTxtQuantidade.getText().equals("") == false){
            Float quantidade = Float.parseFloat(jTxtQuantidade.getText());
            OperacaoController oc = new OperacaoController();
            ProdutoController pc = new ProdutoController();
            ListaController lc = new ListaController();
            int ultimo = oc.buscaUltimo();
            String tipo = oc.buscaTipo(ultimo);
            System.out.println("TIPO: "+ tipo);
        
            if(tipo.equals("S")){
                float teste = produto.getQtdAtual() - quantidade;
                if(teste > produto.getQtdMin()){
                    pc.diminuiQtd(produto.getIdProduto(), quantidade);
                    lc.incluir(ultimo,produto.getIdProduto(), quantidade);
                    atualizaTabelaLista();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Não é possivel, ALERTA QUANTIDADE MÍNIMA", "Controle de Estoque", JOptionPane.INFORMATION_MESSAGE);
                }

            }
            else if(tipo.equals("E")){
                System.out.print("TEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESTE");
                pc.aumentaQtd(produto.getIdProduto(), quantidade);
                lc.incluir(ultimo,produto.getIdProduto(), quantidade);
                atualizaTabelaLista();
            }
        }else {
            JOptionPane.showMessageDialog(this, "ERRO", "Controle de Estoque", JOptionPane.INFORMATION_MESSAGE);
        }
           
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnCliente;
    private javax.swing.ButtonGroup BtnOperacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jCmbCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTblProduto;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtProcura;
    private javax.swing.JTextField jTxtQuantidade;
    // End of variables declaration//GEN-END:variables
}
